{
 "title": "Puppeteer Tests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Tests Launched",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_tests_launched_count", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Tests Completed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_test_seconds_count", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Total Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(promgrep_active_users)" }
   ]
  },
  {
   "title": "Puppeteer Chrome Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_chrome_processes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Browser Logins",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_browser_login_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Test Timeout Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_timeout_error_count", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Tests Failed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promgrep_tests_failed_count)",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Hosts with low users",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    { "expr": "promgrep_active_users<100", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "API Accounts Created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promgrep_accounts_created_count",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Browser Question Transition",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promgrep_question_transition_millis_sum[1m])) by (instance)/sum(rate(promgrep_question_transition_millis_count[1m])) by (instance)",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Test Active Users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_active_users", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Hosts with failures",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "topk(5, promgrep_tests_failed_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container exit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promgrep_test_will_exit" }
   ]
  },
  {
   "title": "Browser Questions Started",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promgrep_question_started_count) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Prova recusada",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promgrep_fail_prova_encerrada_count)",
     "legendFormat": "prova_encerrada"
    },
    {
     "expr": "sum(progrep_fail_questao_fora_ordem_count)",
     "legendFormat": "questao_fora_ordem"
    }
   ]
  },
  {
   "title": "Hosts increasing users",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "delta(promgrep_active_users[5m])>0",
     "legendFormat": "increasing"
    }
   ]
  },
  {
   "title": "Hosts decreasing users",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "delta(promgrep_active_users[5m])<0",
     "legendFormat": "decreasing"
    }
   ]
  },
  {
   "title": "Browser Question Time to Finish",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promgrep_question_finished_millis_sum[1m])) by (instance)/sum(rate(promgrep_question_finished_millis_count[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Browser Questions Started",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promgrep_question_started_count) by (instance)",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Prova conferida com gravação com sucesso",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promgrep_prova_conferida_gravacao_sucesso_count",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Falhas de conferências com gravação",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promgrep_fail_qtde_tela_grava_difere_count)",
     "legendFormat": "qtde_tela_difere_gravada"
    },
    {
     "expr": "sum(promgrep_fail_resposta_gravada_difere_tela_count)",
     "legendFormat": "resposta_gravada_difere_tela"
    },
    {
     "expr": "sum(promgrep_fail_prova_gravada_not_found_count)",
     "legendFormat": "prova_gravada_not_found"
    },
    {
     "expr": "sum(promgrep_fail_texto_gravado_curto_count)",
     "legendFormat": "texto_gravado_curto"
    }
   ]
  }
 ]
}